#!/bin/bash
# Generated by AI for my-local-nas: Pure System Port Raiser & Init

echo "=== Проверка и поднятие портов локального NAS ==="

# 1. Проверяем и принудительно открываем порты на уровне брандмауэра (iptables)
# Если утилиты iptables нет, скрипт попытается её поставить
if ! command -v iptables &> /dev/null; then
    apt update && apt install iptables -y
fi

echo "Применяем правила брандмауэра для портов HTTP (80) и Samba (445)..."
iptables -A INPUT -p tcp --dport 80 -j ACCEPT
iptables -A INPUT -p tcp --dport 445 -j ACCEPT
iptables -A INPUT -p tcp --dport 139 -j ACCEPT
iptables -A INPUT -p udp --dport 137:138 -j ACCEPT

# 2. Проверяем порт 80 (Apache)
if ! ss -tuln | grep -q ":80 "; then
    echo "[!] Порт 80 закрыт. Проверяем наличие Apache..."
    if ! command -v apache2 &> /dev/null; then
        echo "Apache не найден. Устанавливаем и настраиваем автоиндекс..."
        apt update && apt install apache2 -y
        a2enmod autoindex
        rm -f /var/www/html/index.html
    fi
    echo "Запускаем Apache и принудительно поднимаем порт 80..."
    systemctl enable apache2
    systemctl start apache2
else
    echo "[OK] Порт 80 активен (Apache запущен)."
fi

# 3. Проверяем порт 445 (Samba)
if ! ss -tuln | grep -q ":445 "; then
    echo "[!] Порт 445 закрыт. Проверяем наличие Samba..."
    if ! command -v smbd &> /dev/null; then
        echo "Samba не найдена. Устанавливаем пакеты..."
        apt update && apt install samba cifs-utils -y
    fi
    echo "Запускаем Samba и принудительно поднимаем порт 445..."
    systemctl enable smbd
    systemctl start smbd
else
    echo "[OK] Порт 445 активен (Samba запущена)."
fi

echo "=== Все порты успешно заведены и активны! ==="
